import Head from 'next/head'
import Image from 'next/image'

import  Main  from './component/Main'
import About from './component/About'
import Skills from './component/Skills'
import Projects from './component/Projects'
import Contact from './component/Contact'


export default function Home() {
  return (
    <div >
      <Head>
        <title>My Portfolio </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Main/>
      <About/>
      <Skills/>
      <Projects/>
      <Contact/>
      

     
    </div>
  )
}
